services:
  # Layanan 1: Backend FastAPI
  api:
    build: .
    # Perintah untuk menjalankan FastAPI
    command: ["uv", "run", "--no-sync", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Sinkronisasi kode secara real-time (Hot Reload)

  # Layanan 2: Frontend Streamlit
  frontend:
    build: .
    environment:
      - API_BASE_URL=http://api:8000
    # Perintah untuk menjalankan Streamlit
    command: ["uv", "run", "--no-sync", "streamlit", "run", "web/frontend.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - api   # Pastikan API menyala lebih dulu sebelum frontend
